name: CI

on:
pull_request:
    branches: [ main]

job: 
testes:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: instalar dependências
  run: npm install
  - name: rodar testes
  run: npm test